version: "3.7"

services:
    database:
        build:
            context: ./postgres
            dockerfile: Dockerfile
        restart: always
        networks:
            - wifimapper-intra
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: wifi-mapper
        # ports:
        #     - "2345:5432"
        volumes:
            - ./volumes/database:/var/lib/postgresql/data
    wifimapper:
        build:
            context: ./express
            dockerfile: Dockerfile
        restart: always
        networks:
          - wifimapper-intra
          - wifimapper-web
        ports:
            - "9919:3000"
        environment:
            PGUSER: admin
            PGHOST: database
            PGPASSWORD: postgres
            PGDATABASE: wifi-mapper
            PGPORT: 5432
        volumes:
            - ./volumes/wifimapper:/var/www/html

networks:
    wifimapper-web:
        external: true
    wifimapper-intra:
        external: false