version: "3.7"

services:
    database:
        build:
            context: ./postgres
            dockerfile: Dockerfile
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: wifi-mapper
        ports:
            - "2345:5432"
        healthcheck:
            test: ["CMD", "pg_isready", "-U"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        volumes:
            - ./volumes/database:/var/lib/postgresql/data